import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Loading } from '@/components/Loading';
import { Toaster } from 'sonner';
import { TGInitScript } from '@/components/TGInitScript';
import { ClientLazyMotion } from '@/components/ClientLazyMotion';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <ClientLazyMotion>{children}</ClientLazyMotion>
        </main>
        <Toaster
          toastOptions={{
            duration: 1500,
          }}
        />
        <TGInitScript></TGInitScript>

        <Loading></Loading>
      </body>
    </html>
  );
}
